name: Go - Windows

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: go build -o nspm.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nspm.exe
          path: nspm.exe